export const routePaths = {
  managerLogin: '/manager/login',
  home: '/',
  desktopSchedule: '/schedule',
  weeklySchedule: '/schedule/weekly',
  leavePlanner: '/schedule/leave-planner',
  employeeLogin: '/employee/login',
  employeeHome: '/employee',
  employeeSchedule: '/employee/schedule',
  employeeInventory: '/employee/inventory',
  employeeInventoryCheck: '/employee/inventory/check',
  employeeInventoryIncoming: '/employee/inventory/incoming',
  employeeRequests: '/employee/requests',
  manageScheduleBlock: '/schedule/block',
  employees: '/employees',
  addEmployee: '/employees/add',
  removeEmployee: '/employees/remove',
  requestHelp: '/support',
  myRequests: '/requests',
  requestHistory: '/requests/history',
  reports: '/reports',
  inventoryCatalog: '/reports/inventory',
  settings: '/settings',
};