create extension if not exists pgcrypto;

create table if not exists public.app_settings (
  id boolean primary key default true,
  store_name text not null default 'Amazon Cafe',
  manager_phone text not null,
  manager_password text not null,
  preferred_view text not null default 'desktop',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint app_settings_single_row check (id = true)
);

create table if not exists public.employees (
  id bigint primary key generated by default as identity,
  employee_code text not null unique,
  name text not null,
  role text not null,
  avatar text,
  phone text not null unique,
  password text not null,
  active boolean not null default true,
  availability_status text not null default 'ready',
  skills text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint employees_availability_status_check check (availability_status in ('ready', 'annual_leave', 'personal_leave', 'sick_leave', 'absent'))
);

create table if not exists public.employee_availability (
  employee_id bigint not null references public.employees(id) on delete cascade,
  date_key date not null,
  status text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (employee_id, date_key),
  constraint employee_availability_status_check check (status in ('ready', 'annual_leave', 'personal_leave', 'sick_leave', 'absent'))
);

create table if not exists public.calendar_day_settings (
  date_key date primary key,
  leave_locked boolean not null default false,
  double_pay boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.schedule_blocks (
  id bigint primary key,
  date_key date not null default current_date,
  time_label text not null,
  title text not null,
  required integer not null check (required > 0),
  status text not null default 'ok',
  tasks text[] not null default '{}',
  template_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.schedule_block_assignments (
  block_id bigint not null references public.schedule_blocks(id) on delete cascade,
  employee_id bigint not null references public.employees(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (block_id, employee_id)
);

create table if not exists public.requests (
  id bigint primary key generated by default as identity,
  title text not null,
  request_type text,
  detail text,
  attachment_name text,
  status text not null default 'รอดำเนินการ',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.inventory_items (
  id bigint primary key generated by default as identity,
  name text not null,
  category text not null,
  quantity integer not null default 0,
  unit text not null,
  threshold integer not null default 0,
  expires_on date,
  no_expiry boolean not null default false,
  checked_at timestamptz,
  checked_by text,
  received_today integer not null default 0,
  sold_today integer not null default 0,
  use_today boolean not null default false,
  base_quantity integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.inventory_history (
  id bigint primary key generated by default as identity,
  item_id bigint references public.inventory_items(id) on delete cascade,
  action_type text,
  label text not null,
  detail text not null,
  actor_name text,
  logged_at timestamptz not null default now()
);

create table if not exists public.issue_reports (
  id bigint primary key generated by default as identity,
  title text not null,
  detail text not null,
  severity text not null,
  status text not null default 'รอดำเนินการ',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint issue_reports_severity_check check (severity in ('ต่ำ', 'กลาง', 'สูง'))
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_updated_at_app_settings on public.app_settings;
create trigger set_updated_at_app_settings before update on public.app_settings for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_employees on public.employees;
create trigger set_updated_at_employees before update on public.employees for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_employee_availability on public.employee_availability;
create trigger set_updated_at_employee_availability before update on public.employee_availability for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_calendar_day_settings on public.calendar_day_settings;
create trigger set_updated_at_calendar_day_settings before update on public.calendar_day_settings for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_schedule_blocks on public.schedule_blocks;
create trigger set_updated_at_schedule_blocks before update on public.schedule_blocks for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_requests on public.requests;
create trigger set_updated_at_requests before update on public.requests for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_inventory_items on public.inventory_items;
create trigger set_updated_at_inventory_items before update on public.inventory_items for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_issue_reports on public.issue_reports;
create trigger set_updated_at_issue_reports before update on public.issue_reports for each row execute function public.set_updated_at();
